### PR TITLE
Mount extra classpath dependencies in /app

### LINKED ISSUE #3: Support additional SQL drivers
Something like mounting additional classpath entries?

### PR DESCRIPTION
**Pull request by theangrydev**
Rather than bundling e.g. JDBC drivers in the application.

This fixes #3 and allows for JDBC drivers other than Oracle.

### CODE REVIEW

**Comment by theangrydev** [comment]
We should also work on removing the Oracle JAR from the repo and adding instructions on how to get it or something like that. Plus links to non Oracle drivers too maybe. Could bundle drivers that are open source.

**Comment by tjheslin1** [comment]
I definitely will be removing the bundled driver, now the tool is in a usable state (at least once #8 is addressed).

When you mention non-Oracle drivers, are you referring to non-Oracle databases? This will require code changes also as I use OracleDataSource from Hikari.

**Comment by tjheslin1** [comment]
I will document how to get the ojdbc.jar and how to provide it at runtime.

**Comment by theangrydev** [comment]
Yeah, I meant non-Oracle databases. True. You will need a factory somewhere for javax.sql.DataSource or something like that.

**Comment by theangrydev** [comment]
HikariDataSource depends on DataSource. OracleDataSource implements DataSource.

**Pull request merged**
